server:
  port: 8090

spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: customer
      username: admin
      password: admin
      authentication-database: admin

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
